version: '3.8'



services:
  mongo:
    image: mongo:6
    restart: always
    container_name: 'gos-expense-db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: gos-expense
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    network_mode: host

  gos-expense-app:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    network_mode: host
